apiVersion: apps/v1
kind: Deployment
metadata:
  name: nail-care
  labels:
    app.kubernetes.io/name: nail-care
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nail-care
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nail-care
    spec:
      containers:
      - name: nginx
        image: ghcr.io/kuraudo-io/nail_care@sha256:61acffc77a59dc72f3e1088c5784ce8a880a83ad322e36efe3267f39e96a1207
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nail-care
spec:
  selector:
    app.kubernetes.io/name: nail-care
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nail-care-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "go.h4n.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nail-care
            port:
              number: 8080

